Updated libraries and S6, Work in progress

diff --git a/docker/02-patch-fs/etc/cont-init.d/01-init-mysql b/docker/02-patch-fs/etc/cont-init.d/01-init-mysql
--- a/docker/02-patch-fs/etc/cont-init.d/01-init-mysql
+++ b/docker/02-patch-fs/etc/cont-init.d/01-init-mysql
@@ -1,69 +1,71 @@
-#!/usr/bin/env sh
+#!/usr/bin/with-contenv bash
 
-# parameters
-MYSQL_ROOT_PWD=${MYSQL_ROOT_PWD:-"root"}
-MYSQL_USER=${MYSQL_USER:-"developer"}
-MYSQL_USER_PWD=${MYSQL_USER_PWD:-"developer"}
-MYSQL_USER_DB=${MYSQL_USER_DB:-""}
-
-if [ ! -d "/run/mysqld" ]; then
-    mkdir -p /run/mysqld
-    chown -R mysql:mysql /run/mysqld
+### Set Debug Mode
+if [ "$DEBUG_MODE" = "TRUE" ] || [ "$DEBUG_MODE" = "true" ]; then
+    set -x
 fi
 
+if [ -z "$MYSQL_ROOT_PASSWORD" -a -z "$MYSQL_ALLOW_EMPTY_PASSWORD" ]; then
+    echo >&2 '** [mariadb] error: database is uninitialized and MYSQL_ROOT_PASSWORD not set'
+    echo >&2 '    Did you forget to add -e MYSQL_ROOT_PASSWORD=... ?'
+    exit 1
+fi
+
+# Set Character Set
+CHARACTER_SET=${CHARACTER_SET:-"utf8mb4"}
+sed -i -e "s/<CHARACTER_SET>/$CHARACTER_SET/g" /etc/mysql/my.cnf
+
+# Set Default Collation
+CHARACTER_COLLATION=${CHARACTER_COLLATION:-"utf8mb4"}
+sed -i -e "s/<CHARACTER_COLLATION>/$CHARACTER_COLLATION/g" /etc/mysql/my.cnf
+
+### Permissions Fix
+chmod 0644 /etc/mysql/my.cnf
+
+# Check init
 if [ -d /var/lib/mysql/mysql ]; then
-    echo '[i] MySQL directory already present, skipping creation'
+	echo "** [mysql] MySQL directory already present, skipping DB creation."
+  chown -R mysql:mysql /var/lib/mysql
 else
-    echo "[i] MySQL data directory not found, creating initial DBs"
 
-    chown -R mysql:mysql /var/lib/mysql
+  # Init database
+  echo 'Initializing MySQL'
+  mysql_install_db --user=mysql --basedir=/usr --datadir=/var/lib/mysql --defaults-file=/etc/mysql/my.cnf >/dev/null
+  echo 'Database initialized'
 
-    # init database
-    echo 'Initializing database'
-    mysql_install_db --user=mysql > /dev/null
-    echo 'Database initialized'
-
-    echo "[i] MySql root password: $MYSQL_ROOT_PWD"
-
-    # create temp file
-    tfile=`mktemp`
-    if [ ! -f "$tfile" ]; then
-        return 1
-    fi
-
-    # save sql
-    echo "[i] Create temp file: $tfile"
-    cat << EOF > $tfile
-USE mysql;
+  echo 'Initializing customization'
+  TEMP_FILE='/tmp/mysql-first-time.sql'
+  cat > "$TEMP_FILE" <<-EOSQL
+DELETE FROM mysql.user ;
+CREATE USER 'root'@'%' IDENTIFIED BY '${MYSQL_ROOT_PASSWORD}' ;
+GRANT ALL ON *.* TO 'root'@'%' WITH GRANT OPTION ;
+DROP DATABASE IF EXISTS test ;
 FLUSH PRIVILEGES;
-DELETE FROM mysql.user;
-GRANT ALL PRIVILEGES ON *.* TO 'root'@'localhost' IDENTIFIED BY '$MYSQL_ROOT_PWD' WITH GRANT OPTION;
-GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' IDENTIFIED BY '$MYSQL_ROOT_PWD' WITH GRANT OPTION;
-EOF
+EOSQL
 
+  if [[ -n "${MYSQL_USER}" && -n "${MYSQL_DATABASE}" ]]; then
+    DATABASES=$(echo ${MYSQL_DATABASE} | tr "," "\n")
 
-    # Create new database
-    if [ "$MYSQL_USER_DB" != "" ]; then
-        echo "[i] Creating database: $MYSQL_USER_DB"
-        echo "CREATE DATABASE IF NOT EXISTS \`$MYSQL_USER_DB\` CHARACTER SET utf8 COLLATE utf8_general_ci;" >> $tfile
+    for DATABASE in ${DATABASES}
+    do
+      echo "CREATE DATABASE IF NOT EXISTS \`${DATABASE}\`;" >> $TEMP_FILE
+      echo "GRANT ALL PRIVILEGES ON \`${DATABASE}\`.* TO '${MYSQL_USER}'@'%' IDENTIFIED BY '${MYSQL_PASSWORD}';" >> $TEMP_FILE
+    done
 
-        # set new User and Password
-        if [ "$MYSQL_USER" != "" ] && [ "$MYSQL_USER_PWD" != "" ]; then
-        echo "[i] Creating user: $MYSQL_USER with password $MYSQL_USER_PWD"
-        echo "GRANT ALL ON \`$MYSQL_USER_DB\`.* to '$MYSQL_USER'@'%' IDENTIFIED BY '$MYSQL_USER_PWD';" >> $tfile
-        fi
-    else    
-        # don`t need to create new database,Set new User to control all database.
-        if [ "$MYSQL_USER" != "" ] && [ "$MYSQL_USER_PWD" != "" ]; then
-        echo "[i] Creating user: $MYSQL_USER with password $MYSQL_USER_PWD"
-        echo "GRANT ALL ON *.* to '$MYSQL_USER'@'%' IDENTIFIED BY '$MYSQL_USER_PWD';" >> $tfile
-        fi
-    fi
+    echo "FLUSH PRIVILEGES;" >> $TEMP_FILE
+  fi
 
-    echo 'FLUSH PRIVILEGES;' >> $tfile
-    /usr/bin/mysqld --user=mysql --bootstrap --verbose=0 < $tfile
-    rm -f $tfile
+  if [[ -n "${MYSQL_USER}" && -z "${MYSQL_DATABASE}" ]]
+  then
+    echo "CREATE DATABASE IF NOT EXISTS \`${MYSQL_USER}\`;" >> $TEMP_FILE
+    echo "GRANT ALL PRIVILEGES ON \`${MYSQL_USER}\`.* TO '${MYSQL_USER}'@'%' IDENTIFIED BY '${MYSQL_PASSWORD}';" >> $TEMP_FILE
+    echo "FLUSH PRIVILEGES;" >> $TEMP_FILE
+  fi
+
+  /usr/bin/mysqld --defaults-file=/etc/mysql/my.cnf --console --user=mysql --init-file="$TEMP_FILE"
+  rm -f $TEMP_FILE
+
 fi
 
-echo '[i] start running mysqld'
-exec nohup /usr/bin/mysqld --user=mysql --console --sql-mode= > /dev/null 2>&1 &
+mkdir -p /tmp/state/
+echo 'Initialization Complete' >/tmp/state/01-init-mysql
